# config/packages/fos_rest.yaml

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json', prefer_extension: true }
    view:
        view_response_listener: 'force'
