vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
        
    mappings:
       ingredients:
           uri_prefix: /images/ingredients
           upload_destination: '%kernel.project_dir%/public/images/ingredients'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       dish:
            uri_prefix: /images/dish
            upload_destination: '%kernel.project_dir%/public/images/dish'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
