vich_uploader:
    db_driver: orm
    mappings:
        ingredient:
            uri_prefix: /images/ingredients
            upload_destination: '%kernel.project_dir%/public/images/ingredients'
        dish:
            uri_prefix: /images/dish
            upload_destination: '%kernel.project_dir%/public/images/dish'


